name: Publish package

on:
  push:
    tags: ['*']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Borales/actions-yarn@v2.0.0
        with:
          cmd: publish
          auth-token: ${{secrets.GITHUB_TOKEN}}
          registry-url: npm.pkg.github.com
